include open file:// and fix bugs

diff --git a/src/applaunch b/src/applaunch
--- a/src/applaunch
+++ b/src/applaunch
@@ -14,18 +14,17 @@ usage: $(basename $0) [<app_name>]
 
        <app_name>  [optional] app name to start
 
-       Create your ~/.chromerc
+       Create your ~/.applaunchrc
 
        Format:
        app_name | description;url;width,height;positionX,positionY;
 
        Example ~/.chromerc:
        google | Google           ;https://www.google.com;
-       social | Social Networks  ;https://www.twitter.com;800,600;100,100
-       social | Social Networks  ;https://www.facebook.com;
+       twitter| Twitter          ;https://www.twitter.com;800,600;100,100
 
        Execute:
-       $(basename $0) social
+       $(basename $0) twitter
        or
        $(basename $0)
 
@@ -35,83 +34,77 @@ fi
 
 FILTER=$1
 
-while true
+if [ "$FILTER" == "" ]; then
+  echo
+  msg_bold "  applaunch (2020) by fszostak"
+  echo
+  echo "  Select one app using up/down"
+  echo "  keys and enter or return to confirm:"
+
+  IFS=$'\n'
+
+  options=( "--- continue ---" $(cat ~/.applaunchrc | grep -v -e "^$" | grep -v -e "ˆ# "| cut -f1 -d";" | sort -t '|' -k2 | uniq))
+  echo
+
+  select_option "${options[@]}"
+  let choice=$?
+
+  if [ $choice -eq 0 ]; then
+      echo
+      break
+  fi
+
+  APP=$(echo ${options[$choice]} | awk '{print $1}')
+else
+  APP=$FILTER
+fi
+
+if [ $(grep -e "^$APP " ~/.applaunchrc | wc -l) -eq 0 ]; then
+  echo "App \"$APP\" not found in ~/.chromerc"
+  exit
+fi
+
+while read APP_DATA
 do
-  if [ "$FILTER" == "" ]; then
-    echo
-    msg_bold "  applaunch (2020) by fszostak"
-    echo
-    echo "  Select one app using up/down"
-    echo "  keys and enter or return to confirm:"
+  IFS=";"
+  set - $APP_DATA
 
-    IFS=$'\n'
+  THIS_APP=$(echo "$FILTER" | cut -f1 -d' ')
+  URL=$2
+  SIZE=$3
+  POSITION=$4
 
-    options=( "--- continue ---" $(cat ~/.applaunchrc | grep -v -e "^$" | grep -v -e "ˆ# "| cut -f1 -d";" | sort -t '|' -k2 | uniq))
-    echo
+  APP_TYPE=$(echo "$URL" | cut -f1 -d":")
 
-    select_option "${options[@]}"
-    let choice=$?
-
-    if [ $choice -eq 0 ]; then
-        echo
-        break
-    fi
-
-    APP=$(echo ${options[$choice]} | awk '{print $1}')
-  else
-    APP=$FILTER
-  fi
-
-  if [ $(grep -e "^$APP " ~/.applaunchrc | wc -l) -eq 0 ]; then
-    echo "App \"$APP\" not found in ~/.chromerc"
-    exit
-  fi
-
-  while read APP_DATA
-  do
-    IFS=";"
-    set - $APP_DATA
-
-    THIS_APP=$(echo "$FILTER" | cut -f1 -d' ')
-    URL=$2
-    SIZE=$3
-    POSITION=$4
-
-    APP_TYPE=$(echo "$URL" | cut -f1 -d":")
-
-    # Chrome launch
-    if [ "$APP_TYPE" == "http" -o "$APP_TYPE" == "https" ]; then
-      if [ $(ps aux | grep "$URL" | grep -v grep | wc -l) -gt 0 ]; then
-        if [ "$SIZE" != "" ]; then
-          kill -9 $(ps aux | grep "$URL" | grep -v grep | awk '{print $2}')
-          [ $? -eq 0 ] && echo "$THIS_APP - $URL chrome was killed!!!"
-        else
-          echo "$THIS_APP - $URL already running!!!"
-          press_continue
-          continue
-        fi
-      fi
-
-      echo "Starting $THIS_APP - $URL ..."
-
+  # Chrome launch
+  if [ "$APP_TYPE" == "http" -o "$APP_TYPE" == "https" -o "$APP_TYPE" == "file" ]; then
+    if [ $(ps aux | grep "$URL" | grep -v grep | wc -l) -gt 0 ]; then
       if [ "$SIZE" != "" ]; then
-        $CHROME --app="data:text/html,<html><body><script>window.moveTo($POSITION);window.resizeTo($SIZE);window.location='$URL';</script></body></html>" > /dev/null 2>&1 &
+        kill -9 $(ps aux | grep "$URL" | grep -v grep | awk '{print $2}')
+        [ $? -eq 0 ] && echo "$THIS_APP - $URL chrome was killed!!!"
       else
-        $CHROME --app="$URL" > /dev/null 2>&1 &
+        echo "$THIS_APP - $URL already running!!!"
+        continue
       fi
     fi
 
-    # bash command launch
-    if [ "$APP_TYPE" == "bash" ]; then
-      CMD=$(echo "$URL" | cut -f2 -d":")
-      echo "Starting $THIS_APP ..."
-      echo "\$ $CMD"
-      bash -c "$CMD"
-    fi
-    
-    press_continue
+    echo "Starting $THIS_APP - $URL ..."
 
-  done <<EOF
-  $(grep -e "^$APP " ~/.applaunchrc)
+    if [ "$SIZE" != "" ]; then
+       $CHROME --app="data:text/html,<html><body><script>window.moveTo($POSITION);window.resizeTo($SIZE);window.location='$URL';</script></body></html>" > /dev/null 2>&1 &
+    else
+       $CHROME --app="$URL" > /dev/null 2>&1 &
+    fi
+  fi
+
+  # bash command launch
+  if [ "$APP_TYPE" == "bash" ]; then
+    CMD=$(echo "$URL" | cut -f2 -d":")
+    echo "Starting $THIS_APP ..."
+    echo "\$ $CMD"
+    bash -c "$CMD"
+  fi
+  
+done <<EOF
+$(grep -e "^$APP " ~/.applaunchrc)
 EOF
-done
