improvements

diff --git a/src/docker-kill b/src/docker-kill
--- a/src/docker-kill
+++ b/src/docker-kill
@@ -1,8 +1,47 @@
 #!/usr/bin/env bash
 
-while read CONTAINER
-do
-  docker kill $CONTAINER 
-done <<EOF
-$(docker ps | grep "$1" | cut -f1 -d' ')
-EOF
+. ~/scripts/.app-functions.sh
+
+TMP=/tmp/$(basename $0).tmp
+
+if [ "$1" == "-h" -o $# -gt 1 ]; then
+  echo "usage: docker-kill [<filter>]"
+  exit
+fi
+
+if [ $# -eq 1 ]; then
+  docker ps | grep -e "$1\|CONTAINER" | cut -c1-50 > $TMP
+else
+  docker ps | cut -c1-50 > $TMP
+fi
+
+NUM_LINES=$(cat $TMP | wc -l)
+
+if [ $NUM_LINES -eq 1 ]; then
+  echo "No containers running"
+  exit
+fi
+
+echo
+echo "DOCKER KILL"
+echo "Select one option using up/down keys and enter "
+echo "to confirm or CTRL-C to abort:"
+
+IFS=$'\n' 
+options=($(cat $TMP))
+echo
+
+echo "   ${options[0]}"
+unset -v 'options[0]'
+select_option "${options[@]}"
+let choice=$?+1
+
+CONTAINER_ID=$(echo ${options[$choice]} | cut -f1 -d' ')
+
+echo "Kill container..."
+docker kill $CONTAINER_ID 
+
+rm $TMP
+echo
+echo "CONTAINER RUNNING"
+docker ps
diff --git a/src/ssh-plus b/src/ssh-plus
--- a/src/ssh-plus
+++ b/src/ssh-plus
@@ -8,10 +8,11 @@
 if [ "$1" == "-h" ]; then
   cat <<EOF
 
-usage: ssh-plus [-h] [-c] [<filter>]
+usage: ssh-plus [-h|-a|-c] [<filter>]
 
        -h  this informations
-       -c  select new connection method
+       -a  add new host
+       -r  reset connection method
 
        [<filter>]  filter by host
 
@@ -47,7 +48,65 @@ EOF
 fi
 
 echo
-if [ "$1" == "-c" ]; then
+if [ "$1" == "-a" ]; then
+  echo "  Select environment type:"
+  echo
+  options=("PROD" "STAGING" "DEV" "DEVOPS" "LAB")
+  select_option "${options[@]}"
+  choice=$?
+  ADD_Environ==${options[$choice]}
+
+  echo "  Select cloud:"
+  echo
+  options=("aws" "gcloud" "azure" "digitalocean" "on-premisse")
+  select_option "${options[@]}"
+  choice=$?
+  ADD_Cloud==${options[$choice]}
+
+  echo
+  echo -n "Description: "
+  read ADD_Description
+
+  echo
+  echo "Type the ~/.ssh/config data:"
+  echo -n "Host: "
+  read ADD_Host
+  echo -n "  User: "
+  read ADD_User
+  echo -n "  Hostname or IP: "
+  read ADD_HostName
+  echo -n "  PEM file in your .ssh directory (ex.id_rsa.pem): "
+  read ADD_IdentityFile
+
+  if [ "$ADD_Host" == "" -o  \
+       "$ADD_User" == "" -o  \
+       "$ADD_HostName" == "" -o  \
+       "$ADD_IdentityFile" == "" ]; then
+    echo "Error: Insufficient parameters"
+    exit
+  fi 
+      
+  cat <<EOF >>~/.ssh/config
+
+#::  LAB / gcloud / gdpr-file-upload
+#;:
+Host ${ADD_Host}
+     User            ${ADD_User}
+     HostName        ${ADD_HostName}
+     IdentityFile    ~/.ssh/${ADD_IdentityFile}
+     #ForwardAgent    yes
+     #ProxyCommand    ssh -W %h:%p server-gateway
+
+EOF
+
+  echo
+  echo
+  echo "*** $ADD_Host added successfully. Try ssh $ADD_Host"
+  echo
+  exit
+fi
+
+if [ "$1" == "-r" ]; then
   CONNECT="-"
   shift
 else
